feat(cxl-marketing-nav): show search declaratively
conversionxl/aybolit pull request #135
Opened 2021-05-07 11:13 UTC by tomasced

Related issue: https://github.com/conversionxl/jobs-theme/issues/132

2021-05-07 12:44 UTC, lkraav requested changes

2021-05-07 12:44 UTC, lkraav commented on packages/cxl-ui/src/components/cxl-marketing-nav.js
> +  hideSearch = false;
Configurations towards the negative are mentally taxing.

Refactor to `showSearch` instead.

2021-05-07 12:44 UTC, lkraav commented on packages/cxl-ui/src/components/cxl-marketing-nav.js
> +    }
Can we maybe skip whole part of template instead of build-hide?

2021-05-20 13:16 UTC, lkraav requested changes

2021-05-20 13:16 UTC, lkraav commented on packages/cxl-ui/src/components/cxl-marketing-nav.js
> +  isSearchHidden() {
Avoid creating "used once" new symbols.

Can we write what this method does directly into template `?hidden` condition?

2023-07-26 07:05 UTC, pawelkmpt commented
Obsolete

2023-07-26 07:05 UTC, closed without merging