cxl paywall message
conversionxl/aybolit pull request #171
Opened 2021-09-16 13:47 UTC by anoblet

Adds the ability to specify the dialog content from the outside. Constrains are that `<div slot="message"></div>` needs to have only one direct child to act as the wrapper.

```
<cxl-paywall>
  <div slot="message">
    <div id="sample-wrapper">###DIALOG CONTENT###</div>
  </div>
  ###CONTENT###
</cxl-paywall>
```

It should support text/html.

2021-09-22 08:44 UTC, pawelkmpt commented
@anoblet popover with either text or HTML works nicely when limit is reached but before message is visible:

![Screenshot 2021-09-22 at 10 40 13](https://user-images.githubusercontent.com/5165721/134311389-af6b85c9-5a36-445b-a4a8-b14a034a7532.png)

My code

```html
<cxl-paywall _limit="10" opacity="0.2" class="paywall">
    <div slot="message"><span>pay now man</span></div>
    <!-- other content -->
</cxl-paywall>
```

2021-09-22 08:44 UTC, pawelkmpt requested changes
Hide message before it's in popover

2021-09-22 14:23 UTC, anoblet commented
Fixed

2021-09-23 08:41 UTC, pawelkmpt approved these changes

2021-09-23 08:41 UTC, merged