feat(cxl-ui): add external link icon
conversionxl/aybolit pull request #198
Opened 2022-02-04 15:26 UTC by anoblet

2022-05-04 08:15 UTC, pawelkmpt requested changes
Please squash these commits into one

2022-05-04 08:35 UTC, lkraav commented
> Please squash these commits into one

Not sure if it's worth holding up merge for such.

2022-05-04 08:47 UTC, pawelkmpt commented
> Not sure if it's worth holding up merge for such.

Well, you could've merged it while visiting

2022-05-05 04:53 UTC, pawelkmpt approved these changes

2022-05-05 04:53 UTC, merged