Possible patches, refactoring and maybe cleanup.
conversionxl/aybolit pull request #208
Opened 2022-05-17 14:01 UTC by saas786

2022-05-17 14:09 UTC, kylebrodeur commented
Task linked: [CU-2xw2h8u Aybolit review / testing / patches after playbooks -> master merge](https://app.clickup.com/t/2xw2h8u)

2022-05-19 17:42 UTC, anoblet commented
What happened to https://github.com/conversionxl/aybolit/pull/198?

I picked up that error a couple of weeks ago: https://github.com/conversionxl/aybolit/pull/202#discussion_r841630764.

It looks like `CXLPlaybookAccordion` supports a single object argument (https://github.com/conversionxl/aybolit/blob/476764d8fcb147e69b7324563e3f0d64153b476c/packages/storybook/cxl-ui/cxl-vaadin-accordion/cxl-playbook-accordion.story.js#L5)

Maybe use this instead?:

```js
${CXLPlaybookAccordion({ FeedbackButtonLabel: 'Leave feedback', PlaybookId: '1234' })}
```

2022-05-19 17:45 UTC, anoblet requested changes

2022-05-19 17:45 UTC, anoblet commented on packages/storybook/cxl-ui/cxl-paywall/cxl-paywall-layout=2c-l.stories.js
> +        <footer class="entry-footer">${CXLPlaybookAccordion('Leave feedback', '1234')}</footer>
```suggestion
        <footer class="entry-footer">${CXLPlaybookAccordion({ FeedbackButtonLabel: 'Leave feedback', PlaybookId: '1234' })}</footer>
```

2022-05-20 10:35 UTC, saas786 commented
> What happened to the story from https://github.com/conversionxl/aybolit/pull/198?

This has been moved to new general story: https://github.com/conversionxl/aybolit/commit/675f29b71d87c7ee70a2c129b5c7e28524c1d25d

> I picked up on the error a couple of weeks ago: https://github.com/conversionxl/aybolit/pull/202#discussion_r841630764.
> It looks like `CXLPlaybookAccordion` supports a named object argument. Using it would help future-proof things. 

Thanks, I missed it, too many components to look for, PRs etc. Updated the code, should be fine now.

2022-05-20 12:10 UTC, anoblet approved these changes
LGTM

2022-06-06 15:36 UTC, merged