refactor(cxl-lumo-styles): update storybook with current home page styles
conversionxl/aybolit pull request #300
Opened 2023-08-03 18:42 UTC by freudFlintstone

https://app.clickup.com/t/861mhf04m

2023-10-03 14:12 UTC, pawelkmpt reviewed
@freudFlintstone quick glance review on this draft code. I'll go deeper once PR is ready for review

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/_mixins.scss
> +}
Naming them `font-weight-light` etc. would be better

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/_mixins.scss
> +}
It's a wrapper for regular CSS style. Could you explain how this is better then just doing `font-style: italic;` everywhere?

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/_mixins.scss
> +@mixin label {
What kind of label is it? Where should we use it? Please add comment

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/_mixins.scss
> +@mixin body-text {
These look similar and it's no clear for me where should we use each of these. Please add comments.

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/_mixins.scss
> +  font-family: var(cxl-lumo-font-secondary);
`--` missing?

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/themes/vaadin-button.scss
> +  font-size: var(var-lumo-font-size-l) !important;
`--` missing?

2023-10-03 14:12 UTC, pawelkmpt commented on packages/storybook/cxl-lumo-styles/typography.stories.js
> +        <!-- <vaadin-icon slot="suffix" icon="lumo:arrow-right"></vaadin-icon> -->
Why not just delete it?

2023-10-03 14:12 UTC, pawelkmpt commented on packages/storybook/cxl-lumo-styles/typography.stories.js
> +      <!-- <vaadin-icon slot="suffix" icon="lumo:arrow-right"></vaadin-icon> -->
Why not just delete it?

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-lumo-styles/scss/_mixins.scss
> -/*
And here I see you deleted mixins. Could you add some context?

2023-10-03 14:12 UTC, pawelkmpt commented on packages/cxl-ui/scss/cxl-dashboard-header.scss
> +    // line-height: 1.4;
just delete

2023-10-25 13:45 UTC, lkraav requested changes

2023-11-02 00:10 UTC, freudFlintstone commented
Task linked: [CU-861n2cqe7 CXL Style sync](https://app.clickup.com/t/861n2cqe7)

2023-11-21 17:41 UTC, freudFlintstone commented on .gitignore
> +.idea
Looks like it's been there for a while. I'm fixing it in this branch, but we should have specific tasks and PRs for maintenance chores.  
https://github.com/conversionxl/aybolit/commit/639ab2d78171ed2f9f7b8fdf5ba1c9d81e6145ff

2023-11-22 10:16 UTC, pawelkmpt requested changes
@freudFlintstone `yarn build` fails. As you can see, GH couldn't do it either.

![Screenshot 2023-11-22 at 11 15 34](https://github.com/conversionxl/aybolit/assets/5165721/735f96c9-e592-4fdd-8078-4a1b7a955ce5)

2023-11-23 08:32 UTC, pawelkmpt approved these changes

2023-11-23 08:32 UTC, merged