Raphael/fix/dashboard/header initial state
conversionxl/aybolit pull request #325
Opened 2023-09-11 23:24 UTC by freudFlintstone

https://app.clickup.com/t/86ay8ah04

Dependencies: https://github.com/conversionxl/aybolit/pull/324

2023-09-12 09:14 UTC, pawelkmpt submitted a review, later dismissed
Please resolve conflicts

2023-09-12 22:15 UTC, freudFlintstone commented
@pawelkmpt Don't forget this, I couldn't do a re-request for review

2023-09-14 10:45 UTC, pawelkmpt requested changes
@freudFlintstone please resolve conflicts

2023-09-14 12:03 UTC, pawelkmpt approved these changes

2023-09-14 12:03 UTC, merged