fix(cxl-ui): fix course card layout
conversionxl/aybolit pull request #337
Opened 2023-09-26 12:57 UTC by freudFlintstone

https://app.clickup.com/t/86ayagj21

2023-09-27 03:42 UTC, anoblet approved these changes

2023-09-27 18:31 UTC, freudFlintstone commented on packages/storybook/cxl-ui/cxl-course-card/template.js
Note the standard use for the tags slot has changed. To save space and correctly clip overflowing text, a single span element should be used with [slot=tags], containing all categories in a comma separated string.

2023-09-28 11:29 UTC, pawelkmpt requested changes
This view is broken. Please check if just Storybook or bigger issue: https://deploy-preview-337--conversionxl-aybolit.netlify.app/?path=/story/cxl-ui-cxl-course-card--courses-dashboard-different-heights

![Screenshot 2023-09-28 at 13 28 41](https://github.com/conversionxl/aybolit/assets/5165721/b6a36443-9954-4b93-a0c9-0d8371e42c15)

2023-09-28 15:04 UTC, freudFlintstone commented
> This view is broken. Please check if just Storybook or bigger issue: https://deploy-preview-337--conversionxl-aybolit.netlify.app/?path=/story/cxl-ui-cxl-course-card--courses-dashboard-different-heights
> 
> ![Screenshot 2023-09-28 at 13 28 41](https://user-images.githubusercontent.com/5165721/271267605-b6a36443-9954-4b93-a0c9-0d8371e42c15.png)

It was , in fact, only about the storybook layout. But it does also mean we have to consider that when implementing the new institute home page grid.

2023-09-29 08:38 UTC, pawelkmpt approved these changes

2023-09-29 08:39 UTC, merged