feat(cxl-ui): remove accordion and improve dashboard visual architecture
conversionxl/aybolit pull request #348
Opened 2023-10-24 01:33 UTC by freudFlintstone

https://app.clickup.com/t/86ayj5cv3

dependencies: https://github.com/conversionxl/aybolit/pull/346

2023-10-31 10:33 UTC, pawelkmpt requested changes
Squash all commits and change message to

```diff
feat(cxl-ui): add cxl-dashboard-section component

https://app.clickup.com/t/86ayj5cv3
```

2023-11-01 07:56 UTC, heshfekry commented
Task linked: [CU-86ayj5cv3 Break out accordion and improve VA](https://app.clickup.com/t/86ayj5cv3)

2023-11-01 10:26 UTC, HenerHoop commented
@freudFlintstone You were missing an import from there in the index-core file. I added it. WPS won't work otherwise. Ando also renamed Dashboard section class.

2023-11-01 10:53 UTC, HenerHoop commented
@freudFlintstone Fixed height bug and full width description should be limited to a specific width.

![Screenshot 2023-11-01 at 12 51 06](https://github.com/conversionxl/aybolit/assets/70375089/8f6c03f2-78b5-42c6-9679-485689114c4f)

2023-11-01 11:06 UTC, HenerHoop commented on packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-section.stories.js
> +  <cxl-dashboard-section image=${section.image}>
I think we don't need this section image value here.

2023-11-01 11:06 UTC, HenerHoop commented on packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-sections.stories.js
> +        <cxl-dashboard-section image=${cat.image}>
I think we don't need this category image value here.

2023-11-01 11:39 UTC, HenerHoop commented
@freudFlintstone I think we can rebase the master here. Then we'll have the right light card available as well.

2023-11-01 12:05 UTC, freudFlintstone commented
You had an outdated version of the branch in your machine, I'll push mine again and you can make changes you need again.

2023-11-02 10:01 UTC, pawelkmpt commented
> Squash all commits and change message to
> 
> ```diff
> feat(cxl-ui): add cxl-dashboard-section component
> 
> https://app.clickup.com/t/86ayj5cv3
> ```

@freudFlintstone please read comments carefully. You didn't update commit message

2023-11-02 10:10 UTC, HenerHoop commented
> > Squash all commits and change message to
> > ```diff
> > feat(cxl-ui): add cxl-dashboard-section component
> > 
> > https://app.clickup.com/t/86ayj5cv3
> > ```
> 
> @freudFlintstone please read comments carefully. You didn't update commit message

@pawelkmpt It could also have been caused by me because we had a small error there.

2023-11-02 11:43 UTC, freudFlintstone commented
commit message edited

2023-11-02 11:50 UTC, pawelkmpt commented
> @freudFlintstone Category header has a fixed height issue and full width description should be limited to a specific width.
> 
> ![Screenshot 2023-11-01 at 12 51 06](https://user-images.githubusercontent.com/70375089/279653147-8f6c03f2-78b5-42c6-9679-485689114c4f.png)

Is this @HenerHoop will work on now?

2023-11-02 21:04 UTC, pawelkmpt approved these changes

2023-11-07 12:00 UTC, pawelkmpt commented
@freudFlintstone please solve conflicts. They appeared after recent merges

2023-11-08 09:42 UTC, pawelkmpt approved these changes

2023-11-08 09:42 UTC, merged

2023-11-08 09:43 UTC, pawelkmpt commented
Task linked: [CU-86ayjehbf Small changes in dashboard (server-side) to accomodate new layout](https://app.clickup.com/t/86ayjehbf)