feat(cxl-ui): refactor cxl-dashboard-header
conversionxl/aybolit pull request #349
Opened 2023-10-25 12:14 UTC by HenerHoop

https://app.clickup.com/t/86ayhhfgy

2023-10-26 09:08 UTC, pawelkmpt requested changes

2023-10-26 09:08 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-header.js
> +  @property({ type: Boolean }) hasCompletedStats = false;
I think `show` is better in the context of (not)showing a piece of component.

```suggestion
  @property({ type: Boolean }) showCompletedStats = false;
```

2023-10-26 09:08 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-header.js
> +  @property({ type: Boolean }) hasContinueSlider = false;
```suggestion
  @property({ type: Boolean }) showContinueSlider = false;
```

2023-10-27 12:58 UTC, freudFlintstone commented on packages/cxl-lumo-styles/scss/global.scss
> +  --cxl-color-athens-gray: hsla(210, 20%, 96%, 1);
Maybe not to action now, but I think these are being added to the wrong place. There's a colors.scss file, in which we should use theme lumo variables when possible, but should also have the extra variables.

2023-10-27 13:05 UTC, freudFlintstone approved these changes
Nice work

2023-10-31 09:07 UTC, HenerHoop commented
@pawelkmpt I think that this PR is no longer valid because the roadmap block's PR already includes it (with small changes). It was necessary to add it there to see the entire header together.

2023-10-31 09:17 UTC, closed without merging