feat(cxl-ui): add new team dashboard
conversionxl/aybolit pull request #352
Opened 2023-10-27 01:31 UTC by freudFlintstone

https://app.clickup.com/t/86ayd0hrw

2023-10-27 01:32 UTC, freudFlintstone commented
Starting Draft PR so we are able to start testing of each component early. The header is available

2023-10-28 13:25 UTC, heshfekry commented
Solid thank you.

2023-10-31 14:26 UTC, freudFlintstone commented
Task linked: [CU-86ayd0hrw Team dashboard](https://app.clickup.com/t/86ayd0hrw)

2023-11-02 20:17 UTC, pawelkmpt reviewed
Small mobile (320px):
* missing side padding,
* me need more space between stats and progress bar.

<img width="324" alt="Screenshot 2023-11-02 at 21 11 35" src="https://github.com/conversionxl/aybolit/assets/5165721/a7b2bfdd-2551-4a50-bc74-1a0454c9c3bf">

2023-11-02 20:17 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-team-header.js
> +          <a href="my-account/teams/${this.teamId}/settings/">
These links should be passed by attribute. We need flexibility just in case URL changes.

2023-11-02 20:17 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-team-stats.js
> +  @property({ type: String }) teamId = 0;
Why `string`, not `number`?

2023-11-02 20:17 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-team-stats.js
> +            <a href="roadmap/team/?team_id=${this.teamId}">
Should be passed by attribute

2023-11-06 08:24 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-team-header.js
> +          <a href="my-account/teams/${this.teamId}/settings/">
@freudFlintstone this is missing

2023-11-06 08:24 UTC, pawelkmpt commented on packages/cxl-ui/src/components/cxl-dashboard-team-stats.js
> +            <a href="roadmap/team/?team_id=${this.teamId}">
@freudFlintstone this is missing

2023-11-08 13:17 UTC, pawelkmpt requested changes
Commit message changes:

```diff
- feat(cxl-ui): add new team dashboard header
+ feat(cxl-ui): add cxl-dashboard-team-header component
```



```diff
- feat(cxl-ui): add new team dashboard stats
+ feat(cxl-ui): add cxl-dashboard-team-stats component
```


```diff
- feat(cxl-ui): handle cta links in header and stats components
+ feat(cxl-ui): team dashboard - CTA links in header and stats components
```

---

Like usual, broken on small mobile and tablet:

![Screenshot 2023-11-08 at 13 55 28](https://github.com/conversionxl/aybolit/assets/5165721/862efac9-f85e-4894-ae6c-60442603b84c)

![Screenshot 2023-11-08 at 13 55 04](https://github.com/conversionxl/aybolit/assets/5165721/6a7fd44b-c081-491e-96a7-865e8a7f0526)

2023-11-08 13:18 UTC, pawelkmpt commented
Resolve conflicts

2023-11-08 14:22 UTC, freudFlintstone commented
@pawelkmpt [It's not broken](https://deploy-preview-352--conversionxl-aybolit.netlify.app/?path=/story/cxl-ui-cxl-team-dashboard--cxl-dashboard). You probably forgot to run yarn build-styling after changing branches.

2023-11-09 10:03 UTC, pawelkmpt commented
> @pawelkmpt [It's not broken](https://deploy-preview-352--conversionxl-aybolit.netlify.app/?path=/story/cxl-ui-cxl-team-dashboard--cxl-dashboard). You probably forgot to run yarn build-styling after changing branches.

I visually test mostly on the Storybook attached to the PR.

2023-11-09 10:27 UTC, pawelkmpt requested changes
Small mobile 320px

2023-11-14 12:34 UTC, pawelkmpt commented
@freudFlintstone please rebase on top of `master`

2023-11-15 09:57 UTC, pawelkmpt approved these changes

2023-11-15 09:57 UTC, merged