feat(cxl-ui): [cxl-certificate-header] update completed page
conversionxl/aybolit pull request #399
Opened 2024-02-21 14:05 UTC by anoblet

https://app.clickup.com/t/86azbhf5m

2024-02-28 11:46 UTC, pawelkmpt commented
> @anoblet why solution with `MediaQueryController` controller is better than simply hiding credential with CSS?
> 
> Especially in situation when `_wideMediaQuery = '(min-width: 528px)';` is different from CSS MQ values (closest: `$small: 568px`).

@anoblet ping

2024-02-28 13:30 UTC, anoblet commented
@pawelkmpt True. I was unsure which was the best strategy. Updated :)

2024-03-01 09:49 UTC, pawelkmpt requested changes
@anoblet credential picture is suppose to be hidden on mobile and visible from `medium`. Buttons should be always visible though.

2024-03-04 10:53 UTC, pawelkmpt approved these changes

2024-03-04 10:53 UTC, merged